# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6-lts.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/craft-windows-x86-64-qt6.yml

      # Blocked - copied from tokodon
      # - /gitlab-templates/reuse-lint.yml
      # - /gitlab-templates/android-qt6.yml
      # - /gitlab-templates/craft-android-qt6-apks.yml
