# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/karchive': '@stable'
    'frameworks/kwallet': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/purpose': '@stable'

