# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kwallet': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/purpose': '@latest-kf6'
