/* config.h.  Generated by cmake from config.h.cmake  */

#define FALKON_VERSION "${PROJECT_VERSION}"
#cmakedefine FALKON_PLUGIN_PATH "${FALKON_PLUGIN_PATH}"
#cmakedefine FALKON_GIT_REVISION "${FALKON_GIT_REVISION}"

/* Enable portable build */
#cmakedefine PORTABLE_BUILD

/* Disable DBus support */
#cmakedefine DISABLE_DBUS

/* QtWebEngine is at least version 5.10 */
#cmakedefine01 HAVE_QTWEBENGINE_5_10
