# SPDX-FileCopyrightText: 2024 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: falkon
confinement: strict
grade: stable
base: core22
adopt-info: falkon
apps:
    falkon:
        extensions:
        - kde-neon-6
        common-id: org.kde.falkon.desktop
        desktop: usr/share/applications/org.kde.falkon.desktop
        command: usr/bin/falkon
        command-chain:
        - snap/command-chain/desktop-launch6
        plugs:
        - pulseaudio
        - browser-support
plugs:
    gtk-3-themes:
        interface: content
        target: $SNAP/data-dir/themes
        default-provider: gtk-common-themes
    kde-gtk3-themes:
        interface: content
        target: $SNAP/data-dir/themes
        default-provider: qt-common-themes
    gtk-2-themes:
        interface: content
        target: $SNAP/data-dir/themes
        default-provider: gtk-common-themes
    kde-gtk2-themes:
        interface: content
        target: $SNAP/data-dir/themes
        default-provider: qt-common-themes
    qt-icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: qt-common-themes
    gtk-icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    qt-sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: qt-common-themes
    gtk-sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    qt-6-themes:
        interface: content
        target: $SNAP/kf6
        default-provider: qt-common-themes
    dot-config-kde-globals:
        interface: personal-files
        read:
            - $HOME/.config/kdeglobals
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.falkon
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    falkon:
        parse-info:
        - usr/share/metainfo/org.kde.falkon.appdata.xml
        plugin: cmake
        source: .
        source-type: local
        cmake-parameters:
        - -DCMAKE_INSTALL_PREFIX=/usr
        - -DCMAKE_BUILD_TYPE=Release
        - -DQT_MAJOR_VERSION=6
        - -DBUILD_WITH_QT6=ON
        - -DBUILD_TESTING=OFF
        - -DCMAKE_INSTALL_SYSCONFDIR=/etc
        - -DCMAKE_INSTALL_LOCALSTATEDIR=/var
        - -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON
        - -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
        - -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON
        - -DCMAKE_INSTALL_RUNSTATEDIR=/run
        - -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON
        - -DCMAKE_VERBOSE_MAKEFILE=ON
        - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
        - --log-level=STATUS
        - -DCMAKE_LIBRARY_PATH=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
        prime:
        - -usr/lib/*/cmake/*
        - -usr/include/*
        - -usr/share/ECM/*
        - -usr/share/man/*
        - -usr/share/icons/breeze-dark*
        - -usr/bin/X11
        - -usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0
        - -usr/lib/aspell/*
        - -usr/share/lintian
    cleanup:
        after:
        - falkon
        plugin: nil
        build-snaps:
        - core22
        - kf6-core22
        - qt-common-themes
        override-prime: |
            set -eux
            for snap in "core22" "kf6-core22" "qt-common-themes"; do
                cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
            done


