[Icon Theme]
Name=Breeze
Name[ca]=Brisa
Name[nl]=Breeze
Name[pt]=Brisa
Name[sv]=Breeze
Name[uk]=Breeze
Name[x-test]=xxBreezexx
Comment=Breeze Team
Comment[ca]=L'equip Brisa
Comment[nl]=Breeze-team
Comment[pt]=Equipa do Brisa
Comment[sv]=Breeze-gruppen
Comment[uk]=Команда Breeze
Comment[x-test]=xxBreeze Teamxx
DisplayDepth=32
Inherits=default
Directories=16x16,22x22,32x32

[16x16]
Size=16

[22x22]
Size=22

[32x32]
Size=32
