find_path(LibIntl_INCLUDE_DIRS NAMES libintl.h)
find_library(LibIntl_LIBRARIES NAMES intl libintl)
include(CheckCXXSymbolExists)
check_cxx_symbol_exists(gettext libintl.h LibIntl_SYMBOL_FOUND)
if (LibIntl_SYMBOL_FOUND)
    set(LibIntl_FOUND TRUE)
else()
    set(LibIntl_FOUND FALSE)
endif()
